### ISSUE TITLE
Compress does not throw error and gets trapped in await

### ISSUE THREAD

**Issue by andrewdavidcostello** [TonyBrobston/jpegasus#167]
Something is happening with the attached image where no error is thrown and the image is not compressed. I unfortunately don't have time to leave it running right now and will try to update this with more information if I can. For now I will have to set a timeout and wrap the compress in a promise.

First problem I have had with this library though!

![0008](https://user-images.githubusercontent.com/443964/93996053-acd1d100-fd89-11ea-844f-e2bdbcb9ff2c.jpg)

**Comment by TonyBrobston** [comment]
@andrewdavidcostello Thank you for reporting this issue and providing this image, this is a huge help!

I've put a test together that should be valid. The test fails because of jest's timeout, which is 5 seconds; this happens because like you mentioned it's stuck in the promise. I'm not sure of what the fix is yet. On a side note, I kind of regret implementing exif orientation stuff; this is out of scope an has just caused me problems.

https://github.com/TonyBrobston/jpegasus/pull/168

**Comment by TonyBrobston** [comment]
Actually... I just realized the issue and the solution I believe. Seems like it just never calls `resolve` after parsing all the bytes. In this case we'll assume orientation wasn't able to be found and resolve `-1`.

**Comment by andrewdavidcostello** [comment]
Glad it was a quick solution, once you release a new version I will give it a test. Unfortunately I had to switch libraries for now to resolve this (so might take a little while) but I much preferred this one so would be nice to drop it back in. I am not sure if this is related but I also saw this in Sentry:

```
<anonymous> in DataView.getUint16
Called from: ../node_modules/jpegasus/lib/services/exifService.js in parseBytes
RangeError: Offset is outside the bounds of the DataView
```

I don't have any more information on that one but you may be able to tell if it is a similar issue I hope!

**Comment by TonyBrobston** [comment]
@andrewdavidcostello That's good to know. I may be able to write a test that recreates that and then resolve it. Thanks again.

**Comment by TonyBrobston** [comment]
@andrewdavidcostello This fix is deployed. I'll be updating my demo site shortly and I'll confirm it's working there. It was tested at a unit level, so it should work at an integration level.

**Comment by TonyBrobston** [comment]
The demo site is deployed, looks like it's working now.
