### ISSUE TITLE
new feature Scale up and down images?

### ISSUE THREAD

**Issue by weilinzung** [TonyBrobston/jpegasus#99]
new feature Scale up and down images?

**Comment by TonyBrobston** [comment]
@weilinzung Can you elaborate?

Do you mean like width/height of the image? If so, are you looking for an option like `scaleDimensionsBy`? In this case if you wanted all images to be half the size you could pass `0.5` and if you want to say double them you'd pass `2`? Assuming you have a use case this seems reasonable to me.

**Comment by weilinzung** [comment]
@TonyBrobston you are correct, I want to be able to scale image width & height and keep the ratio.

Does the option of `scaleDimensionsBy` already exist?

**Comment by TonyBrobston** [comment]
@weilinzung It does not. 

However I'm open to trying to implement it. If you're familiar with test driven development and typescript I'm accepting pull requests; if not I'll likely get to it in the next few days or possibly in a week or two.

**Comment by weilinzung** [comment]
@TonyBrobston Appreciated and I think that would be very helpful. I think I can try to create the functions but maybe would not happen sooner than you.

**Comment by TonyBrobston** [comment]
@weilinzung I guess we'll see who gets to it first. If you make the changes I can give you a shout-out by adding you to the contributors list. But no biggie if not.

Another thing to consider is if someone was to use `scaleDimensionsBy` with `maxHeight` and/or `maxWidth`. I would thinking if they set either max `jpegasus` should still respect that. 

So I'd say three tests need added here (one for `scaleDimensionsBy` with `maxHeight`, one for `scaleDimensionsBy` with `maxWidth`, one for `scaleDimensionsBy` with no max):
https://github.com/TonyBrobston/jpegasus/blob/master/tests/services/scaleService.test.ts

One or two tests here:
https://github.com/TonyBrobston/jpegasus/blob/master/tests/services/optionService.test.ts

An update to the readme:
https://github.com/TonyBrobston/jpegasus/blob/master/README.md

**Comment by TonyBrobston** [comment]
Here's the start of the PR. I need to pass the last two tests, unfortunately it's getting late and I'm not thinking clearly.

https://github.com/TonyBrobston/jpegasus/pull/107

**Comment by weilinzung** [comment]
looks cool. I think you are far ahead than me. Do you need any helps or you will do the last two tests?

**Comment by TonyBrobston** [comment]
@weilinzung This PR has been merged (https://github.com/TonyBrobston/jpegasus/pull/108) and I cut a release, you'll see `scaleImageBy` in `1.11.0`.

Let me know how it works for you and if you have any other feature requests.

**Comment by TonyBrobston** [comment]
You can also try it out here: https://tonybrobston.github.io/jpegasus-demo/

**Comment by weilinzung** [comment]
@TonyBrobston Just got a chance to test the new version, but I got an error with React.

    "jpegasus": "^1.9.55" works fine!

`Unhandled Rejection (TypeError): Cannot read property 'compress' of undefined`

```
        const image = await jpegasus.compress(file, {
          quality: 0.9,
        });
```

**Comment by weilinzung** [comment]
after I change from `import jpegasus from 'jpegasus';` to `const jpegasus = require('jpegasus');` that would works again!
